//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeRates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExchangeRates.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not write into configuration file (username/AppData/Septima_Consulting/ExchangeRates/1.0.0.0/user.config).
        /// </summary>
        internal static string ConfigFileOpenException {
            get {
                return ResourceManager.GetString("ConfigFileOpenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russia.
        /// </summary>
        internal static string countrySiteNameRussia {
            get {
                return ResourceManager.GetString("countrySiteNameRussia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukraine.
        /// </summary>
        internal static string countrySiteNameUkraine {
            get {
                return ResourceManager.GetString("countrySiteNameUkraine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully inserted exchange rates in database with codes.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExchangeRates.
        /// </summary>
        internal static string trauHover {
            get {
                return ResourceManager.GetString("trauHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program will now work automatically.
        /// </summary>
        internal static string trayText {
            get {
                return ResourceManager.GetString("trayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExchangeRates.
        /// </summary>
        internal static string trayTitle {
            get {
                return ResourceManager.GetString("trayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program has already inserted exchange rates in databases with codes:.
        /// </summary>
        internal static string warningTodayIsDone {
            get {
                return ResourceManager.GetString("warningTodayIsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ) program has already inserted exchange rates in database with codes:.
        /// </summary>
        internal static string warningTodayIsDone2 {
            get {
                return ResourceManager.GetString("warningTodayIsDone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to proceed?.
        /// </summary>
        internal static string warningTodayIsDone3 {
            get {
                return ResourceManager.GetString("warningTodayIsDone3", resourceCulture);
            }
        }
    }
}
